#!/bin/bash

function tcp_port_in_use {
	lsof -i TCP:$1
}

function yrm {
  echo | rm $@
}

function migration-ts {
	ruby -e 'puts Time.now.strftime("%Y%m%d%H%M%S")' | pbcopy
	pbpaste
}

function get_cellar {
	if [[ `uname -m` == 'arm64' ]]; then
		echo "/opt/homebrew/Cellar"
	else
	  echo "/usr/local/Cellar"
	fi
}


function rec_rm_ds_store {
  find . -name '.DS_Store' -type f -delete
}

function sd_dir {
  echo "$HOME/gdrive/Writing"
}

function sd {
  log_date=$(date +%Y-%m-%d)
  filename="`sd_dir`/$1/${log_date}_log.md"

  if [ ! -f $filename ]; then
    echo "# ${log_date}" > $filename
    echo "$filename created"
    cat "`sd_dir`/log_template.txt" >> $filename
  fi
}

function cl {
    sd "work"
}

function resize_down_50 {
		jpegoptim $1 --strip-exif
		convert $1 -resize 50% $1
}

function loop_rspec {
  echo "Looping $1 10 times"
  for i in {1..10}
  do
    echo "$i pass"
    bundle exec rspec $1
  done
}

function dir_stats {
    # https://unix.stackexchange.com/questions/18506/recursive-statistics-on-file-types-in-directory
    find . -type f -printf '%f\n' | sed -r -n 's/.+(\..*)$/\1/p' | sort | uniq -c
}

function verify_flac {
  find -name "*.flac" -exec ffmpeg -i {} {}.wav \;
  ls -Q *.flac.wav | xargs -L 1 lac | less
  rm *.flac.wav
}

function flac_to_wav {
		fd --extension 'flac' . -exec bash -c 'ffmpeg -y -i "{}" "${1%.*}.wav"' bash {} \;
}

function gnome_bg_color {
  gsettings set org.gnome.desktop.background picture-uri none
  gsettings set org.gnome.desktop.background primary-color '#038387'
  gsettings set org.gnome.desktop.background color-shading-type 'solid'
}

function convert_gif_to_png {
  convert *.gif[1] -set filename:base "%[basename]" "%[filename:base].png"
}

function rspec_on_change {
  bin/rspec $(git ls-files --modified spec/)
}

# ========================== JEST =============================

function jest_loop {
  while true;
  do
    npx jest $1
  done
}

function jest_debug {
  node --inspect-brk node_modules/.bin/jest --runInBand
}

# ========================== GIT ==============================
function gp {
		git log -S $1
}

function gr {
		git rebase -i HEAD~$(git log --oneline "master..$(git branch --show-current)" | wc -l | sed 's/ //g')
}

function nx-drop-shadow {
    defaults write com.apple.screencapture disable-shadow true
}

# fancy branch
function gfb {
    git checkout $(git branch --sort=-committerdate --format "%(refname:short)%(HEAD)" |  tr -d "*" | tr -d " " | fzf --preview="git show --color=always {}")
}

# ==== DOCKER
docker::ssh() {
  local container_id=$(docker ps | grep -v CONTAINER | fzf | cut -d ' ' -f1)
  docker exec -it $container_id /bin/sh
}

docker::id() {
  docker ps | grep -v CONTAINER | fzf | cut -d ' ' -f1 | pbcopy
}

docker::rm() {
  local container_id=$(docker ps -a | grep -v CONTAINER | fzf | cut -d ' ' -f1)
  docker stop $container_id
  docker rm $container_id
}

docker::stop() {
  local container_id=$(docker ps | grep -v CONTAINER | fzf | cut -d ' ' -f1)
  docker stop $container_id
}

fsed() {
  local search=$1
  local replace=$2
  local search_path=$3

  test -z $1 && echo "request search regex" && return;
  test -z $2 && echo "need replace" && return;

  ag -l $search $search_path  | xargs -I {} sed -i'' "s#$search#$replace#g" {}
}

pretty='--pretty=format:%C(green)%h%C(yellow)%d%Creset %s %C(cyan)%an, %ar%Creset'
prettylong='--pretty=format:%C(green)%H%C(yellow)%d%Creset %s %C(cyan)%an, %ar%Creset'

alias gl='git log "$pretty" --graph -n 12'
alias gll='git log "$prettylong" --graph -n 12'
alias gp="git add --all && git diff --cached" # think prepare

function git-files() {
  git ls-tree --full-tree -r --name-only HEAD
}
